#!/usr/bin/env php
<?php

$commands = [
    'publish:config' => function () {
        if (!is_dir(__DIR__ . '/../../../config/vendor/validator')) {
            mkdir(__DIR__ . '/../../../config/vendor/validator', recursive: true);
        }
        copy(__DIR__ . '/config/database.php', __DIR__ . '/../../../config/vendor/validator/database.php');
        copy(__DIR__ . '/config/messages.php', __DIR__ . '/../../../config/vendor/validator/messages.php');
    },
];

$command = $argv[1] ?? null;
if ($command && isset($commands[$command])) {
    $commands[$command]();
} else {
    echo "Usage: php xentixar [command]\n";
    echo "Commands:\n";
    foreach (array_keys($commands) as $cmd) {
        echo "  - $cmd\n";
    }
}